name: Publish Python ðŸ distribution ðŸ“¦ to PyPI

on: push

jobs:
  check:
    name: Check distribution ðŸ“¦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        pip install twine
        build
        --user
    - name: Twine Check
      run: python3 -m twine check dist/*
      
  build:
    name: Build Distribution ðŸ“¦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        pip install twine
        build
        --user
    - name: Twine Check
      run: python3 -m twine build
    - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI }}
          repository-url: https://pypi.org/legacy/
